services:
  #A background worker that consumes a queue
  - type: worker
    name: utubeitbot
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 -m bot
    repo: https://github.com/oVo-HxBots/Utubeitbot.git
    branch: master
    plan: pro ultra
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID 
        sync: false
      - key: CLIENT_SECRET 
        sync: false
      - key: BOT_OWNER 
        sync: false 
      - key: AUTH_USERS 
        sync: false
      - key: UPLOAD_MODE
        value: public
    autoDeploy: true # optional
    disk:
      name: utube-data
      mountPath: /opt/src
      sizeGB: 10
